baseURL = '/'
languageCode = 'en-us'
title = 'SDET Interview Preparation Kit'
# theme = 'terminal-minimal'
theme = 'naturalist-core'

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = 'solarized-light'

[params]
  description = 'Everything you need to crack SDET interviews.'
