baseURL = 'https://notxkcd.github.io/sdet-prep-site/'
languageCode = 'en-us'
title = 'SDET Interview Preparation Kit'
# theme = 'terminal-minimal'
theme = 'naturalist-core'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      taskList = true
      table = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = 'solarized-light'
    noClasses = true

[params]
  description = 'Everything you need to crack SDET interviews.'
